class CfgPatches
{
	class TSG_Characters_F
	{
		units[]=
		{
			"TSG_SoldierDCP_F",
			"TSG_SoldierDCP_AR_F",
			"TSG_SoldierDCP_SL_F",
			"TSG_AssaultPack_dcp",
			"TSG_Kitbag_dcp",
			"TSG_TacticalPack_dcp",
			"TSG_Carryall_dcp",
			"TSG_SoldierDSAPB_F",
			"TSG_SoldierDSAPB_AR_F",
			"TSG_SoldierDSAPB_SL_F",
			"TSG_AssaultPack_dsapb",
			"TSG_Kitbag_dsapb",
			"TSG_TacticalPack_dsapb",
			"TSG_Carryall_dsapb",
			"TSG_SoldierDSAPG_F",
			"TSG_SoldierDSAPG_AR_F",
			"TSG_SoldierDSAPG_SL_F",
			"TSG_AssaultPack_dsapg",
			"TSG_Kitbag_dsapg",
			"TSG_TacticalPack_dsapg",
			"TSG_Carryall_dsapg",
			"TSG_SoldierDTP_F",
			"TSG_SoldierDTP_AR_F",
			"TSG_SoldierDTP_SL_F",
			"TSG_AssaultPack_dtp",
			"TSG_Kitbag_dtp",
			"TSG_TacticalPack_dtp",
			"TSG_Carryall_dtp"
		};
		weapons[]=
		{
			"TSG_CombatUniform_dcp",
			"TSG_CombatUniform_dcp_tshirt",
			"TSG_CombatUniform_dcp_vest",
			"TSG_HelmetB_dcp",
			"TSG_HelmetB_light_dcp",
			"TSG_HelmetSpecB_dcp",
			"TSG_Booniehat_dcp",
			"TSG_MilCap_dcp",
			"TSG_BandollierB_dcp",
			"TSG_PlateCarrier1_dcp",
			"TSG_PlateCarrier2_dcp",
			"TSG_Chestrig_dcp",
			"TSG_CombatUniform_dsapb",
			"TSG_CombatUniform_dsapb_tshirt",
			"TSG_CombatUniform_dsapb_vest",
			"TSG_HelmetB_dsapb",
			"TSG_HelmetB_light_dsapb",
			"TSG_HelmetSpecB_dsapb",
			"TSG_Booniehat_dsapb",
			"TSG_MilCap_dsapb",
			"TSG_BandollierB_dsapb",
			"TSG_PlateCarrier1_dsapb",
			"TSG_PlateCarrier2_dsapb",
			"TSG_Chestrig_dsapb",
			"TSG_CombatUniform_dsapg",
			"TSG_CombatUniform_dsapg_tshirt",
			"TSG_CombatUniform_dsapg_vest",
			"TSG_HelmetB_dsapg",
			"TSG_HelmetB_light_dsapg",
			"TSG_HelmetSpecB_dsapg",
			"TSG_Booniehat_dsapg",
			"TSG_MilCap_dsapg",
			"TSG_BandollierB_dsapg",
			"TSG_PlateCarrier1_dsapg",
			"TSG_PlateCarrier2_dsapg",
			"TSG_Chestrig_dsapg",
			"TSG_CombatUniform_dtp",
			"TSG_CombatUniform_dtp_tshirt",
			"TSG_CombatUniform_dtp_vest",
			"TSG_HelmetB_dtp",
			"TSG_HelmetB_light_dtp",
			"TSG_HelmetSpecB_dtp",
			"TSG_Booniehat_dtp",
			"TSG_MilCap_dtp",
			"TSG_BandollierB_dtp",
			"TSG_PlateCarrier1_dtp",
			"TSG_PlateCarrier2_dtp",
			"TSG_Chestrig_dtp"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F"
		};
	};
};

#include "cfgVehicles.hpp"
#include "cfgWeapons.hpp"